### Pima dataset using radom forest

In [1]:
# import libraries that we need
import pandas as pd
import numpy as np

In [2]:
# read the dataset file using pandas library
df = pd.read_csv('pima_ds.csv')
df.head(4)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0

In [4]:
# print columns of the data
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
columns =['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
          'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']

labels = df['Outcome'].values # will be list of zeros and ones
features = df[list(columns)].values

In [8]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
# split the data to training ad testing data
x_train, x_test, y_train, y_test = train_test_split(features, labels,
                                                    test_size=0.30)
# use the RandomForestClassifier
clf = RandomForestClassifier(n_estimators=1)

clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [10]:
# show the accuracy of model for training data
accuracy = clf.score(x_train, y_train)
v = format(accuracy * 100, '.2f')
print('The accuracy of this model is {}%'.format(v))

The accuracy of this model is 87.15%


In [11]:
# show the accuracy of model for testing data
accuracy = clf.score(x_test, y_test)
v = format(accuracy * 100, '.2f')
print('The accuracy of this model is {}%'.format(v))

The accuracy of this model is 67.53%


In [12]:
# print classification report for model performace
from sklearn.metrics import classification_report

ypredict = clf.predict(x_train)
print('Training classification_report\n',
      classification_report(y_train, ypredict))

Training classification_report
               precision    recall  f1-score   support

           0       0.89      0.92      0.90       357
           1       0.82      0.78      0.80       180

    accuracy                           0.87       537
   macro avg       0.86      0.85      0.85       537
weighted avg       0.87      0.87      0.87       537



In [13]:
# print confusion matrix for model performace

from sklearn.metrics import confusion_matrix

print('confusion_matrix of training\n', confusion_matrix(y_train, ypredict))

# [true positive, false negative]
# [false positive, true negative]

confusion_matrix of training
 [[327  30]
 [ 39 141]]


In [14]:
# confusion_matrix for testing data
ypredict = clf.predict(x_test)
print('Testing classification_report\n',
      classification_report(y_test, ypredict))

print('confusion_matrix of testing\n', confusion_matrix(y_test, ypredict))


Testing classification_report
               precision    recall  f1-score   support

           0       0.71      0.80      0.75       143
           1       0.59      0.48      0.53        88

    accuracy                           0.68       231
   macro avg       0.65      0.64      0.64       231
weighted avg       0.67      0.68      0.67       231

confusion_matrix of testing
 [[114  29]
 [ 46  42]]


## Improve model performance

In [21]:
# trying to use StandardScaler to improve the model prediction accuracy 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [22]:
clf = RandomForestClassifier(n_estimators=1)
clf = clf.fit(x_train, y_train)

accuracy = clf.score(x_train, y_train)
print(' اداء النموذج في عينة التدريب بدقة ', accuracy*100)

accuracy = clf.score(x_test, y_test)
print(' اداء النموذج في عينة الفحص بدقة ', accuracy*100)

ypredict = clf.predict(x_train)
print('\n Training classification report\n',
      classification_report(y_train, ypredict))
print("\n Confusion matrix of training \n",
      confusion_matrix(y_train, ypredict))

ypredict = clf.predict(x_test)
print('\n Testing classification report\n',
      classification_report(y_test, ypredict))
print("\n Confusion matrix of Testing \n",
      confusion_matrix(y_test, ypredict))

 اداء النموذج في عينة التدريب بدقة  88.45437616387338
 اداء النموذج في عينة الفحص بدقة  71.42857142857143

 Training classification report
               precision    recall  f1-score   support

           0       0.92      0.89      0.91       344
           1       0.82      0.87      0.84       193

    accuracy                           0.88       537
   macro avg       0.87      0.88      0.88       537
weighted avg       0.89      0.88      0.89       537


 Confusion matrix of training 
 [[307  37]
 [ 25 168]]

 Testing classification report
               precision    recall  f1-score   support

           0       0.82      0.74      0.78       156
           1       0.55      0.67      0.60        75

    accuracy                           0.71       231
   macro avg       0.69      0.70      0.69       231
weighted avg       0.73      0.71      0.72       231


 Confusion matrix of Testing 
 [[115  41]
 [ 25  50]]
